namespace Feliz

open System
open Fable.Core

[<Erase>]
type ReactDOM =

    /// <summary>
    /// `createRoot` lets you create a root to display React components inside a browser DOM node.
    /// </summary>
    [<ImportMember("react-dom/client")>]
    static member createRoot(container: Browser.Types.HTMLElement) : IReactRoot = jsNative

    /// <summary>
    /// `hydrateRoot` lets you display React components inside a browser DOM node whose HTML content was previously generated by `react-dom/server`.
    /// </summary>
    [<ImportMember("react-dom/client")>]
    static member hydrateRoot(domNode, reactNode, ?options: obj) = jsNative

    /// <summary>
    /// Renders a React element into the DOM in the supplied container and returns a reference to the component (or null for stateless components).
    /// This is the primary entry point into the DOM and is the most common way to render a React application.
    /// </summary>
    /// <param name="element">The React element to render.</param>
    /// <param name="domNode">Some DOM node, such as those returned by document.getElementById(). The node must already exist. 
    /// Passing a different DOM node during an update will cause the portal content to be recreated.</param>
    /// <param name="key">An optional key to identify the portal.</param>
    [<ImportMember("react-dom")>]
    static member createPortal
        (element: ReactElement, domNode: Browser.Types.HTMLElement)
        : ReactElement =
        jsNative

    /// <summary>
    /// Renders a React element into the DOM in the supplied container and returns a reference to the component (or null for stateless components).
    /// This is the primary entry point into the DOM and is the most common way to render a React application.
    /// </summary>
    /// <param name="element">The React element to render.</param>
    /// <param name="domNode">Some DOM node, such as those returned by document.getElementById(). The node must already exist. 
    /// Passing a different DOM node during an update will cause the portal content to be recreated.</param>
    /// <param name="key">An optional key to identify the portal.</param>
    [<ImportMember("react-dom")>]
    static member createPortal
        (element: ReactElement, domNode: Browser.Types.HTMLElement, key: string)
        : ReactElement =
        jsNative

    /// <summary>
    /// Renders a React element into the DOM in the supplied container and returns a reference to the component (or null for stateless components).
    /// This is the primary entry point into the DOM and is the most common way to render a React application.
    /// </summary>
    /// <param name="element">The React element to render.</param>
    /// <param name="domNode">Some DOM node, such as those returned by document.getElementById(). The node must already exist. 
    /// Passing a different DOM node during an update will cause the portal content to be recreated.</param>
    /// <param name="key">An optional key to identify the portal.</param>
    [<ImportMember("react-dom")>]
    static member createPortal
        (element: ReactElement, domNode: Browser.Types.HTMLElement, key: int)
        : ReactElement =
        jsNative

    /// <summary>
    /// Renders a React element into the DOM in the supplied container and returns a reference to the component (or null for stateless components).
    /// This is the primary entry point into the DOM and is the most common way to render a React application.
    /// </summary>
    /// <param name="element">The React element to render.</param>
    /// <param name="domNode">Some DOM node, such as those returned by document.getElementById(). The node must already exist. 
    /// Passing a different DOM node during an update will cause the portal content to be recreated.</param>
    /// <param name="key">An optional key to identify the portal.</param>
    [<ImportMember("react-dom")>]
    static member createPortal
        (element: ReactElement, domNode: Browser.Types.HTMLElement, key: float)
        : ReactElement =
        jsNative

/// The ReactDOMServer object enables you to render components to static markup.
[<Erase>]
type ReactDOMServer =
    /// Render a React element to its initial HTML. React will return an HTML string. You can use this method to generate HTML on the server and send the markup down on the initial request for faster page loads and to allow search engines to crawl your pages for SEO purposes.
    [<ImportMember("react-dom/server")>]
    static member renderToString(element: ReactElement) : string = jsNative

    /// Similar to renderToString, except this doesn’t create extra DOM attributes that React uses internally, such as data-reactroot. This is useful if you want to use React as a simple static page generator, as stripping away the extra attributes can save some bytes.
    ///
    /// If you plan to use React on the client to make the markup interactive, do not use this method. Instead, use `renderToString` on the server and `ReactDOM.hydrate()` on the client.
    [<ImportMember("react-dom/server")>]
    static member renderToStaticMarkup(element: ReactElement, ?options: obj) : string = jsNative

    /// <summary>
    /// `renderToReadableStream` renders a React tree to a [Readable Web Stream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream).
    [<ImportMember("react-dom/server")>]
    static member renderToReadableStream(element: ReactElement, ?options: obj) : JS.Promise<obj> = jsNative

    /// <summary>
    /// `renderToPipeableStream` renders a React tree to a [Node.js Stream](https://nodejs.org/api/stream.html).
    /// </summary>
    [<ImportMember("react-dom/server")>]
    static member renderToPipeableStream(element: ReactElement, ?options: obj) : JS.Promise<obj> = jsNative


